services:
  - type: web
    name: frontend-quote-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: NODE_VERSION
        value: 20.16.0
